import { z } from 'zod';
import type { CCCResult, Layer1Candidate } from '@/lib/ccc-engine/types';

const DEFAULT_MODEL = 'gemini-2.5-flash';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models';

export interface CompanyContext {
  fabricTypes: string[];
  buyerTypes?: string[];
  month: number;
  revenueRange: string;
  companyName?: string;
  city?: string;
  dataSource?: string;
}

export interface Recommendation {
  id: string;
  dimension: Layer1Candidate['dimension'];
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  title: string;
  explanation: string;
  actionSteps: string[];
  estimatedDaysReduction: number;
  estimatedCashFreedLakhs: number;
}

export interface GeminiRecommendationPayload {
  cccResult: CCCResult;
  companyContext: CompanyContext;
  layer1Candidates: Layer1Candidate[];
}

const RecommendationSchema = z.object({
  id: z.string(),
  dimension: z.enum(['DIO', 'DSO', 'DPO']),
  priority: z.enum(['HIGH', 'MEDIUM', 'LOW']),
  title: z.string(),
  explanation: z.string(),
  actionSteps: z.array(z.string()).min(3).max(3),
  estimatedDaysReduction: z.number(),
  estimatedCashFreedLakhs: z.number(),
});

const GeminiPayloadSchema = z.object({
  recommendations: z.array(RecommendationSchema).min(1).max(5),
});

export async function enrichRecommendationsWithGemini(
  payload: GeminiRecommendationPayload
): Promise<Recommendation[]> {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey.startsWith('your_') || apiKey.includes('demo')) {
    throw new Error('Gemini API key is not configured.');
  }

  const model = process.env.GEMINI_MODEL || DEFAULT_MODEL;
  const endpoint = `${GEMINI_API_URL}/${encodeURIComponent(model)}:generateContent`;
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-goog-api-key': apiKey,
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `${SYSTEM_PROMPT}\n\nInput JSON:\n${JSON.stringify(payload)}`,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.2,
        responseMimeType: 'application/json',
        responseJsonSchema: RESPONSE_SCHEMA,
      },
    }),
  });

  const body = (await response.json().catch(() => null)) as GeminiResponse | GeminiError | null;

  if (!response.ok) {
    throw new Error(getGeminiErrorMessage(body, response.status));
  }

  const text = extractGeminiText(body);
  const parsed = GeminiPayloadSchema.parse(JSON.parse(extractJson(text)));

  return parsed.recommendations.slice(0, 5);
}

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
}

interface GeminiError {
  error?: {
    message?: string;
  };
}

const SYSTEM_PROMPT = `You are a working capital analyst specialising in Indian textile manufacturing.
You receive a structured CCC analysis for a textile business and a list of candidate recommendations generated by a deterministic rule engine.
Your job is not to invent a new analysis. Re-rank and enrich the provided candidates.
Tasks:
1. Rank candidates by real-world impact given company context: fabric types, buyer mix, revenue scale, month, and seasonality.
2. Suppress contradictory or irrelevant candidates.
3. Return at most 5 recommendations.
4. Use plain language that an accounts manager, mill owner, or finance intern can understand.
5. Each recommendation needs a concise title, a two-sentence explanation, exactly 3 concrete action steps for this week, estimated days reduction, and estimated cash freed in lakhs of rupees.
Return only JSON matching the provided schema.`;

const RESPONSE_SCHEMA = {
  type: 'object',
  properties: {
    recommendations: {
      type: 'array',
      minItems: 1,
      maxItems: 5,
      description: 'Ranked recommendations, highest real-world working-capital impact first.',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'The id of the original Layer 1 candidate.' },
          dimension: {
            type: 'string',
            enum: ['DIO', 'DSO', 'DPO'],
            description: 'The metric this recommendation primarily improves.',
          },
          priority: {
            type: 'string',
            enum: ['HIGH', 'MEDIUM', 'LOW'],
            description: 'Priority based on cash impact and urgency.',
          },
          title: {
            type: 'string',
            description: 'Plain-language title without finance jargon.',
          },
          explanation: {
            type: 'string',
            description: 'Two short sentences explaining why this matters.',
          },
          actionSteps: {
            type: 'array',
            minItems: 3,
            maxItems: 3,
            items: { type: 'string' },
            description: 'Three concrete actions the user can take this week.',
          },
          estimatedDaysReduction: {
            type: 'number',
            minimum: 0,
            description: 'Estimated number of days reduced from the cash cycle.',
          },
          estimatedCashFreedLakhs: {
            type: 'number',
            minimum: 0,
            description: 'Estimated cash freed in lakhs of rupees.',
          },
        },
        required: [
          'id',
          'dimension',
          'priority',
          'title',
          'explanation',
          'actionSteps',
          'estimatedDaysReduction',
          'estimatedCashFreedLakhs',
        ],
      },
    },
  },
  required: ['recommendations'],
};

function extractGeminiText(body: GeminiResponse | GeminiError | null): string {
  const text = (body as GeminiResponse | null)?.candidates?.[0]?.content?.parts
    ?.map((part) => part.text ?? '')
    .join('')
    .trim();

  if (!text) {
    throw new Error('Gemini returned an empty response.');
  }

  return text;
}

function extractJson(text: string): string {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');

  if (start === -1 || end === -1 || end <= start) {
    throw new Error('Gemini response did not contain JSON.');
  }

  return text.slice(start, end + 1);
}

function getGeminiErrorMessage(body: GeminiResponse | GeminiError | null, status: number): string {
  const apiMessage = (body as GeminiError | null)?.error?.message;
  return apiMessage ? `Gemini API error: ${apiMessage}` : `Gemini API request failed with ${status}.`;
}
